spring:
  cloud:
      openfeign:
        client:
          config:
            clients:
              url: http://localhost:8081/clients
            staff:
              url: http://localhost:8084/staff
            services:
              url: http://localhost:8082/services
